spring.application.name=mpesa-integrations

server.port=8080
# Database
spring.datasource.url=${DB_URL:}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# Mpesa Daraja
mpesa.daraja.consumer-key=${MPESA_CONSUMER_KEY:}
mpesa.daraja.consumer-secret=${MPESA_CONSUMER_SECRET:}
mpesa.daraja.passkey=${MPESA_PASSKEY:}
mpesa.daraja.shortcode=${MPESA_SHORTCODE:174379}
mpesa.daraja.callback-url=${MPESA_STK_CALLBACK_URL:}
mpesa.daraja.callback-token-secret=${MPESA_CALLBACK_TOKEN_SECRET:}
mpesa.daraja.callback-security-enabled=true
mpesa.daraja.baseUrl=https://sandbox.safaricom.co.ke
mpesa.daraja.transactionType=CustomerPayBillOnline

# Logging
logging.level.com.mpesa.integration=DEBUG
