spring.application.name=mpesa-integrations

server.port=8080
# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/payment_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin}

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# Mpesa Daraja
mpesa.daraja.consumer-key=${MPESA_CONSUMER_KEY:2CMUwcM26XcRS9UGOstZvSdPCObWyOToA2vI9tsDvKQhVTHv}
mpesa.daraja.consumer-secret=${MPESA_CONSUMER_SECRET:4xCN6twW7dGqb1JFjPNIwn2Tu2tJq3lYlhlO5OEgEnGmaNiXHk1B7Z7yHnKnnMt2}
mpesa.daraja.passkey=${MPESA_PASSKEY:bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919}
mpesa.daraja.shortcode=${MPESA_SHORTCODE:174379}
mpesa.daraja.callback-url=${MPESA_STK_CALLBACK_URL:https://inalienable-mazily-cleora.ngrok-free.dev/api/v1/payments/callback/a79976f7-9787-4148-ac5c-a199dd2f426f}
mpesa.daraja.callback-token-secret=${MPESA_CALLBACK_TOKEN_SECRET:a79976f7-9787-4148-ac5c-a199dd2f426f}
mpesa.daraja.callback-security-enabled=true
mpesa.daraja.baseUrl=https://sandbox.safaricom.co.ke
mpesa.daraja.transactionType=CustomerPayBillOnline

# Logging
logging.level.com.mpesa.integration=DEBUG
